version: "3.9"
services:
  server:
    build: server
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./frontend/build:/etc/ytdl-web/static:ro
    container_name: ytdl_web
    restart: unless-stopped